apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nginx-d762"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nginx-d762"
  template:
    metadata:
      labels:
        app: "nginx-d762"
    spec:
      containers:
        - name: "nginx-d762"
          image: "containerregistryaoj.azurecr.io/nginx"
          ports:
          - containerPort: 90