apiVersion: v1
kind: Service
metadata:
    name: "nginx-d762"
    labels:
        app: "nginx-d762"
spec:
    type: LoadBalancer
    ports:
    - port: 90
      targetPort: 90
      protocol: TCP
      name: http
    selector:
        app: "nginx-d762"